//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace World_of_Warcraft_Downloader.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/Asandru/World-of-Warcraft-Downloader/raw/master/torrents/World" +
            "_of_Warcraft_1.12.1.torrent")]
        public string WoWD_DLink1 {
            get {
                return ((string)(this["WoWD_DLink1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/Asandru/World-of-Warcraft-Downloader/raw/master/torrents/World" +
            "_of_Warcraft_2.4.3.torrent")]
        public string WoWD_DLink2 {
            get {
                return ((string)(this["WoWD_DLink2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/Asandru/World-of-Warcraft-Downloader/raw/master/torrents/World" +
            "_of_Warcraft_3.3.5a.torrent")]
        public string WoWD_DLink3 {
            get {
                return ((string)(this["WoWD_DLink3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/Asandru/World-of-Warcraft-Downloader/raw/master/torrents/World" +
            "_of_Warcraft_4.3.4.torrent")]
        public string WoWD_DLink4 {
            get {
                return ((string)(this["WoWD_DLink4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/Asandru/World-of-Warcraft-Downloader/raw/master/torrents/World" +
            "_of_Warcraft_5.4.8.torrent")]
        public string WoWD_DLink5 {
            get {
                return ((string)(this["WoWD_DLink5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://github.com/Asandru/World-of-Warcraft-Downloader/raw/master/torrents/World" +
            "_of_Warcraft_6.2.3.torrent")]
        public string WoWD_DLink6 {
            get {
                return ((string)(this["WoWD_DLink6"]));
            }
        }
    }
}
